setwd('F://lol')
getwd()
install.packages('arules')
install.packages('factoextra')
install.packages('caret')
install.packages('C5.0')
install.packages('rlang')
library(rlang)
library(C5.0)
library(factoextra)
library(data.table)
library(dplyr)
detach("package:arules", unload=TRUE)
library(arules)
library(caret)
library(ggplot2)
#rm(list = ls())
